### ISSUE TITLE
Download binaries to `PRE_COMMIT_HOME`

### ISSUE THREAD

**Issue by mattyclarkson** [jlebar/pre-commit-hooks#14]
A common pattern when using `pre-commit` in the CI is the following:

- Override `PRE_COMMIT_HOME = cache/pre-commit`
- Tell the CI system to cache the `PRE_COMMIT_HOME` path
- Then we don't initialise the virtual environments multiple times

This doesn't work well with that because the cache for the clang format binary is separate to the location of the initialised virtual environment.

I would recommend downloading to a local cache director `Path(__file__).parent / ".cache"`:

- `pre-commit` automatically attempts to deduplicate pre-commit hooks in the shared `PRE_COMMIT_HOME` location
- we would naturally work with normal suggested caching of `pre-commit` hooks on CI systems
- It is expected that once a hook is "initialized" it is good to go

Or, if not that, at least default to `PRE_COMMIT_HOME` first.

_Originally posted by @mattyclarkson in https://github.com/jlebar/pre-commit-hooks/pull/13#r704632971_

**Comment by jlebar** [comment]
sgtm

**Comment by asottile** [comment]
please do not pollute `PRE_COMMIT_HOME` -- your tool does not own that cache directory so writing there is inappropriate

**Comment by mattyclarkson** [comment]
Noted. We should document that this downloads to the users natural cache directory.

I actually got a missing executable error when I ran on my CI. Will double check what occurred there.
