### ISSUE TITLE
Submit PR to pre-commit hooks list

### ISSUE THREAD

**Issue by TheButlah** [jlebar/pre-commit-hooks#2]
Given that this repo better supports bazel buildifier than the alternative hook listed at https://pre-commit.com/hooks.html, it would be good to add this repo to that list. That way people like me can more easily find this hook.

**Comment by jlebar** [comment]
Thank you for the bug report, and I'm sorry I didn't see it.  Somehow I had notifications turned off for this repository, I'm really embarrassed.

Fixed in https://github.com/pre-commit/pre-commit/commit/9324084e078b125400b1d369f3a7b9c8940f5615.
