### ISSUE TITLE
clang-format won't work if temp is on a different disk than your home directory

### ISSUE THREAD

**Issue by admorgan** [jlebar/pre-commit-hooks#5]
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\morgana\\AppData\\Local\\Temp\\tmprfxe2o8y\\clang-format' -> 'e:\\home\\.cache\\pre-commit-jlebar\\clang-format-d4afd4eba27022f5f6d518133aebde57281677c9'

**Comment by martukas** [comment]
Same issue in Ubuntu 20. Apparently ine 53 in `clang_format.y` is the culprit.
Seems like this solves it in a non-portable way:
`Path(outfile.name).rename(dest) --> os.system(f"mv {Path(outfile.name)} {dest}")`
But also, allegedly this has been reported to work:
`shutil.move(Path(outfile.name), dest)`

**Comment by admorgan** [comment]
How is Path().rename not portable? These functions are all part of the stdlib.

The problem with both of those solutions is that mv is not atomic. Therefore you have a significantly higher probability of either having left over temporary files and/or partial copies if something goes wrong. Just creating the temp on the same drive has the advantage of guaranteeing atomic operations.

**Comment by jlebar** [comment]
I'm very sorry for missing all this for a month.  :(
